In [ ]:
#We import the libraries
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
#We use panda to transform the csv to dataframe located in the directory data
unemployment = pd.read_csv('/workspaces/Machine-Learning-6-SIN-A-Mar-Jul-2026/data/country_total.csv')

In [ ]:
#We use type to see the type od data unemployment is, in this case a dataframe
type(unemployment)

pandas.DataFrame

In [ ]:
#We use .head() to read the first 5 rows
unemployment.head()

  country seasonality    month  unemployment  unemployment_rate
0      at         nsa  1993.01        171000                4.5
1      at         nsa  1993.02        175000                4.6
2      at         nsa  1993.03        166000                4.4
3      at         nsa  1993.04        157000                4.1
4      at         nsa  1993.05        147000                3.9

In [ ]:
#We use .shape to see the amount of rows and columns
unemployment.shape

(20796, 5)

In [ ]:
# We use .colums to see the columns of our dataframe
unemployment.columns

Index(['country', 'seasonality', 'month', 'unemployment', 'unemployment_rate'], dtype='str')

In [ ]:
#We use .dtypes to see the type of data belonging to the items on the columns
unemployment.dtypes

country                  str
seasonality              str
month                float64
unemployment           int64
unemployment_rate    float64
dtype: object

In [ ]:
# We use .describe() to get the statistic summary of the dataframe
unemployment.describe()

              month  unemployment  unemployment_rate
count  20796.000000  2.079600e+04       19851.000000
mean    1999.401290  7.900818e+05           8.179764
std        7.483751  1.015280e+06           3.922533
min     1983.010000  2.000000e+03           1.100000
25%     1994.090000  1.400000e+05           5.200000
50%     2001.010000  3.100000e+05           7.600000
75%     2006.010000  1.262250e+06          10.000000
max     2010.120000  4.773000e+06          20.900000