In [ ]:
#We import the libraries
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
#We use panda to transform the csv to dataframe located in the directory data
unemployment = pd.read_csv('/workspaces/Machine-Learning-6-SIN-A-Mar-Jul-2026/data/country_total.csv')

In [ ]:
#We use type to see the type od data unemployment is, in this case a dataframe
type(unemployment)

pandas.DataFrame

In [ ]:
#We use .head() to read the first 5 rows
unemployment.head()

  country seasonality    month  unemployment  unemployment_rate
0      at         nsa  1993.01        171000                4.5
1      at         nsa  1993.02        175000                4.6
2      at         nsa  1993.03        166000                4.4
3      at         nsa  1993.04        157000                4.1
4      at         nsa  1993.05        147000                3.9

In [ ]:
#We use .shape to see the amount of rows and columns
unemployment.shape

(20796, 5)

In [ ]:
# We use .colums to see the columns of our dataframe
unemployment.columns

Index(['country', 'seasonality', 'month', 'unemployment', 'unemployment_rate'], dtype='str')

In [ ]:
#We use .dtypes to see the type of data belonging to the items on the columns
unemployment.dtypes

country                  str
seasonality              str
month                float64
unemployment           int64
unemployment_rate    float64
dtype: object

In [ ]:
# We use .describe() to get the statistic summary of the dataframe
unemployment.describe()

              month  unemployment  unemployment_rate
count  20796.000000  2.079600e+04       19851.000000
mean    1999.401290  7.900818e+05           8.179764
std        7.483751  1.015280e+06           3.922533
min     1983.010000  2.000000e+03           1.100000
25%     1994.090000  1.400000e+05           5.200000
50%     2001.010000  3.100000e+05           7.600000
75%     2006.010000  1.262250e+06          10.000000
max     2010.120000  4.773000e+06          20.900000

In [ ]:
#Creating a list
my_list = ['a','b','c','d','e','f']

In [ ]:
#Asking to print he list from the second item and on
my_list[2:]

['c', 'd', 'e', 'f']

In [ ]:
#We are asking the list to print the item, from the longitude of the list minus 4, and on
my_list[len(my_list)-4:]

['c', 'd', 'e', 'f']

In [17]:
countries = pd.read_csv('/workspaces/Machine-Learning-6-SIN-A-Mar-Jul-2026/data/countries.csv')

In [22]:
countries.head(10)

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
0,at,AT,eu,Austria,Autriche,Österreich,47.696554,13.345980
1,be,BE,eu,Belgium,Belgique,Belgien,50.501045,4.476674
2,bg,BG,eu,Bulgaria,Bulgarie,Bulgarien,42.725674,25.482322
3,hr,HR,non-eu,Croatia,Croatie,Kroatien,44.746643,15.340844
4,cy,CY,eu,Cyprus,Chypre,Zypern,35.129141,33.428682
5,cz,CZ,eu,Czech Republic,République tchèque,Tschechische Republik,49.803531,15.474998
6,dk,DK,eu,Denmark,Danemark,Dänemark,55.939684,9.516689
7,ee,EE,eu,Estonia,Estonie,Estland,58.592469,25.806950
8,fi,FI,eu,Finland,Finlande,Finnland,64.950159,26.067564
9,fr,FR,eu,France,France,Frankreich,46.710994,1.718561

In [18]:
countries.shape

(30, 8)

In [19]:
countries.describe()

        latitude  longitude
count  30.000000  30.000000
mean   49.092609  14.324579
std     7.956624  11.257010
min    35.129141  -8.239122
25%    43.230916   6.979186
50%    49.238087  14.941462
75%    54.090400  23.351690
max    64.950159  35.439795

In [20]:
countries.columns

Index(['country', 'google_country_code', 'country_group', 'name_en', 'name_fr',
       'name_de', 'latitude', 'longitude'],
      dtype='str')

In [21]:
countries.dtypes

country                    str
google_country_code        str
country_group              str
name_en                    str
name_fr                    str
name_de                    str
latitude               float64
longitude              float64
dtype: object